version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo pip3 install --requirement requirements.txt
      - run:
          name: Run Tests
          command: python3 -m unittest --verbose
      - run:
          name: Run Pyre
          command: pyre check